include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    camel_case_extensions: true
    constant_identifier_names: true
    directives_ordering: true
    file_names: true
    non_constant_identifier_names: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_await_in_return: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    curly_braces_in_flow_control_structures: true
    empty_catches: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    invalid_annotation_target: ignore
